
---
title: "Discussion"
---

**Limitations**

There were a number of design limitations that serve as potential explanations for the lack of interaction effects between self-control depletion and loss framing. Conducting the experiment outside of a controlled lab setting introduced a number of complexities that likely influenced results. Despite the use of section dividers between stations, administration of anonymized IDs, and limited oversight by the experimenters, it is likely that participants did not feel fully anonymous, and in turn, may not have been as willing to engage in cheating behavior. The style of recruiting, which required direct interaction with the experimenter, as well as the collection of email addresses (despite explanation that these would be used solely to contact the participant should they win), also contributed to the lack of anonymity.

In addition, insufficient incentivization likely caused some of our unanticipated results. Raffle tickets that provide an unknown probability of winning a payout at a future date introduces a number of factors that may have influenced participant behavior. Most notably, raffle tickets impart a much weaker emotional reaction than cash rewards. This is in part due to raffle tickets having an unsure probability of winning as well as raffle tickets having a future payout instead of immediate gratification. It is our opinion that utilizing cash would have dramatically increased the frequency and magnitude of cheating realized, as the reward for cheating would become much more salient. 

Finally, there may have been a selection bias in our subject pool that prevented cheating behavior from occurring. The nature of recruitment may have introduced unintended consequences in regards to the influence on cheating behavior. It may have been the case that at a research university, where students are familiar with such a process, they empathized with the difficulty of running an experiment and gathering sufficient data, and felt they were helping the experimenters out, rather than trying to maximize their payout. If such empathy existed towards the researchers, the likelihood of engaging in cheating behavior would likely have been reduced, as empathy has often been associated with morality.

**Research Extension**

It is also possible that participants were experiencing cognitive load as opposed to cognitive depletion as a result of our task, which may also explain our surprising results. When a participant is under a loaded state, it has been found that they are less likely to engage in cheating behavior as they simply can’t take on the additional computational effort involved (Van’t Veer et al., 2014). There exists a prevalence of misattribution between load and depletion in the existing literature. For example, one study intended to measure the effect of cognitive depletion first asked participants to memorize either a 2-digit or 7-digit number while completing another task (reflecting cognitive load), and were then offered either fruit or chocolate cake (reflecting a cognitively depleting decision), (Shiv et. al, 1999). Just as the two mechanisms were confounded in this experiment, it is possible that a task previously determined to effectively produce a depletion effect actually results in a loaded effect. 

Thus, a relevant  extension to our experiment would be a modification to address the impact of cognitive load on cheating behavior, taking a novel approach that provides insight into the impact of gain or loss framing while under cognitive load.  The primary purpose of such research would be to investigate whether the results will find similarities between ego depletion and cognitive load, arguing that cognitive load increases deception in individuals, or whether the results will support the theory that cognitive load reduces deception, as lying requires more cognitive energy than telling the truth (Van’t Veer et al., 2014). Further, we are interested in exploring whether the gain or loss framing produces similar results under cognitive load and ego depletion (i.e. an increase in deceptive behavior under the loss frame condition).

**Conclusion**

People often face multiple competing influences when making a decision – especially those containing elements of ethicality. Understanding the interplay between the many competing heuristics, contextual influences, and biases can provide useful insights into the cognitive processes that underlie these difficult choices.  Two such factors – self-control depletion and framing effects – have both been shown to play meaningful roles in this important area of study.  Prior research conducted by Grolleau et al., (2016) suggests that people are more likely to cheat when faced with a loss than when faced with a gain while a study conducted by Mead et al., (2009) found that self-control depletion led to an increase in cheating behaviors. Yet, most research into the effects of biases and heuristics on cheating behavior has generally been conducted independently.  In an effort to address this research gap, we instead set out to examine the combined effect of self-control depletion and framing effects on cheating behavior using a two-by-two experimental design.

Overall, participants in our study cheated less frequently than participants in previous studies using a similar task (Mead et al., 2009; Grolleau et al., 2016).  The results supported our hypothesis that participants under the loss condition cheated to a greater magnitude than those under the gain condition, yet the sample size, and thus the lack of power, limits our confidence in generalizing this outcome. Additionally, these findings do not support our hypothesis that participants who were presented with a loss after being depleted cheated more than those in the other treatment conditions.

Despite not supporting all of our main hypotheses, these findings offer several meaningful contributions to this field of study.  The absence of cheating behavior was likely due, in part, to our incentive structure, which relied upon the distribution of raffle tickets.  If, in fact, that is the case, this outcome suggests that further research into the framing effects on non-monetary incentives is warranted.  The ineffectiveness of our depletion task also points to the challenge of systematically creating a state of self-control depletion and the possibility that depletion tasks are actually creating a state of cognitive load.  To examine if – and how – these two distinct concepts impact cheating behavior, we  suggest pursuing a modified experimental design that varies conditions across these two factors.

We hope that this analysis has contributed to the understanding of the impacts of framing effects and self-control depletion on cheating behavior and, based on our lessons learned, serves as a useful roadmap for further research.

